name: pgaff
channels:
  - https://repo.prefix.dev/ecoscope-workflows
  - conda-forge
dependencies:
  - ecoscope-workflows-core=0.0.66
  - ecoscope-workflows-ext-ecoscope=0.0.66
  - python>=3.10.12
  - pip
  - pytest
  - git
  - jupyterlab
  - geopandas<=0.14.2
  - numpy<2.0
  - python-dotenv
  - python-kaleido
  - pip:
    - playwright
    - pytest-playwright
    - python-docx
    - mammoth
    - docx2pdf
